version: '3.8'
services:
#Servizio keycloak
  keycloak-db:
    image: postgres:16.2
    volumes:
      - keyclok-db01-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - postgres-db-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - keycloak-db
    networks:
      - postgres-db-network

    dck-db01:
        image: docker.io/library/postgres:16
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - postgres-db01-volume:/var/lib/postgresql/data
        ports:
            - 5433:5432
        networks:
            - postgres-db-network
    erpapp:
        build:
            context: ./erpapp
            dockerfile: src/docker/Dockerfile
        ports:
            - "8080:8080"
        container_name: erpapp
        networks:
            - postgres-db-network
        depends_on:
            - dck-db01
volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ddalpra/Sviluppo/spring-podman/data
    postgres-db01-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ddalpra/Sviluppo/spring-podman/data01
    keyclok-db01-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/ddalpra/Sviluppo/spring-podman/keycloak01
networks:
    postgres-db-network:
        name: postgres-db-network
        driver: bridge
    backend:
        name: backend
        driver: bridge
